// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPWb0t8SDj0J94fWIYFuALuPGq_iJSJE',
    appId: '1:1047323918502:web:131fa08db5ac8c86f5f467',
    messagingSenderId: '1047323918502',
    projectId: 'fir-connect-e09ff',
    authDomain: 'fir-connect-e09ff.firebaseapp.com',
    storageBucket: 'fir-connect-e09ff.appspot.com',
    measurementId: 'G-QM39MLZYFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6o-abUfIoP6hc1_aHHgeckMVHyfVgF8',
    appId: '1:1047323918502:android:6b67b8d35eabe23af5f467',
    messagingSenderId: '1047323918502',
    projectId: 'fir-connect-e09ff',
    storageBucket: 'fir-connect-e09ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcLVKjgwgOnqK-a-9vOzvXzSuyLtHTB98',
    appId: '1:1047323918502:ios:9c49d1deb8cc74f8f5f467',
    messagingSenderId: '1047323918502',
    projectId: 'fir-connect-e09ff',
    storageBucket: 'fir-connect-e09ff.appspot.com',
    iosClientId: '1047323918502-cumdn51ds3ep2sm7l6lsat0o4v3jrna5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcLVKjgwgOnqK-a-9vOzvXzSuyLtHTB98',
    appId: '1:1047323918502:ios:9c49d1deb8cc74f8f5f467',
    messagingSenderId: '1047323918502',
    projectId: 'fir-connect-e09ff',
    storageBucket: 'fir-connect-e09ff.appspot.com',
    iosClientId: '1047323918502-cumdn51ds3ep2sm7l6lsat0o4v3jrna5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
